Add option to disable loggers in all Simulator structs
JuliaMolSim/Molly.jl pull request #129
Opened 2023-05-22 00:10 UTC by ejmeitz

Thoughts on adding `run_loggers` parameter to all Simulator structs? I noticed it exists in the `StepestDescentMinimizer` but not other things like `VelocityVerlet`.

I ran into a use case where I would like to disable logging in the VV scheme and then re-enable it later. Could also be worth allowing users to change what gets logged in-between calls to `simulate!` within the same code (maybe you can do this already I dunno).

I have not gone thru and made all the necessary changes just wanted to open this to discussion.

2023-05-22 18:11 UTC, jgreener64 commented
Yes I'm up for adding `run_loggers` to all the simulators. It is on the to-do list but I haven't got round to it yet. It would be a good PR if you have the time.

2023-05-22 23:44 UTC, ejmeitz commented
Added `run_loggers` to every simulator besides the REMD ones as those looked a little different and I did not feel confident modifying that code. Also thinking about adding `enable_loggers(sim)`, `disable_loggers(sim)` and `modify_loggers(sys)`. The first two I am not sure are possible because the simulation structs are not mutable.

Default is set to true for everything besides `SteepestDescentMinimizer`

2023-05-24 12:02 UTC, ejmeitz commented
Nah the REMD code was pretty easy to read I've just never looked at it before. I made changes to that in a separate commit if you would like to see #2268ccd. Let me know if that looks alright.

I also moved run_loggers to simulate! instead of being a simulator property. This way its not in an immutable struct and can actually be toggled.

2023-05-24 15:19 UTC, jgreener64 requested changes
Looks good, some minor comments.

2023-05-24 15:19 UTC, jgreener64 commented on src/simulators.jl
> +    simulate!(system, simulator, n_steps; n_threads=Threads.nthreads(), run_loggers = Bool)
`run_loggers=true`. Then below could add "`run_loggers` is `true` by default except for `SteepestDescentMinimizer`".

2023-05-24 15:19 UTC, jgreener64 commented on src/simulators.jl
> +                    run_loggers = false)
No spaces round `=` in arguments for consistency.

2023-05-24 15:19 UTC, jgreener64 commented on src/simulators.jl
> +    return simulate_remd!(sys, sim, n_steps; rng=rng, n_threads=n_threads, run_loggers)
`run_loggers=run_loggers` for consistency (and above).

2023-05-24 15:19 UTC, jgreener64 commented on src/simulators.jl
> +                        run_loggers = true)
This should be passed through to the `Threads.@spawn simulate!` call to control those loggers too. With that I think the REMD strategy is okay, i.e. `run_loggers` turns on/off both types of logger. Maybe we could add a `run_exchange_loggers` later if required.

2023-05-24 15:19 UTC, jgreener64 commented on src/simulators.jl
> +                   run_loggers = true) where {D, G, T}
Remove the reference to `log_states` from the docstring. Also there is a test that calls `log_states` which will need to change.

2023-05-25 11:39 UTC, merged